name: MakeCode

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
      - name: npm install
        run: |
          npm install -g pxt
          pxt target arcade
      - name: build
        run: |
          pxt install
          pxt build --cloud
        env:
          CI: true
